---
# blueteam_password: "qwerQWER1234!@#$"
# scoring_ip: # uncomment only when we know the scoring IP, otherwise skip
backup_dir: "/usr/share/fonts/roboto-mono"
quarantine: "/usr/share/fonts/quar-mono"
firewall_logging: true
logging_ports: [1514, 1515, 1516, 55000, 9200, 443, 9000, 9020]

packet_users:
  - harold
  - francis
  - williams

