---
# blueteam_password: "qwerQWER1234!@#$"
# scoring_ip: # uncomment only when we know the scoring IP, otherwise skip
backup_dir: "/usr/share/fonts/roboto-mono"
quarantine: "/usr/share/fonts/quar-mono"
audit_dir: "/opt/audit"
password_manager_ip: ""
stabvest_controller_ip: ""
# If controller is NOT in scope, leave variable empty. 
# If controller IS in scope, include the IP/subnet that should be allowed on all firewalls
controller_in_scope_allow_ip: ""
subnet: "192.168.1.0/24" # for linux dynamic inventory
linux_inventory_output_file: "" # for linux dynamic inventory - what james requested (list of linux IPs)
control_output_dir: "/tmp" # for linux dynamic inventory
firewall_logging: true
logging_ports: [3000, 3100]
packet_users:
  - harold
  - francis
  - williams
important_files_for_backup:
  - 