- name: Allow port 10250
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 10250
    jump: ACCEPT
  with_items: "{{ groups['kube'] }}"
  loop_control:
    loop_var: kube_ip
  vars:
    source: "{{ kube_ip }}"

- name: Allow port 10256
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 10256
    jump: ACCEPT
  with_items: "{{ groups['kubemgr'] + groups['kube'] }}"
  loop_control:
    loop_var: kube_ip
  vars:
    source: "{{ kube_ip }}"

# - name: Allow NodePort default range
#   iptables:
#     chain: INPUT
#     protocol: tcp
#     destination_ports: 
#      - "30000:32767"
#     jump: ACCEPT